# For Genre, Category and Title
NAME_LENGTH = 256
SLUG_LENGTH = 50
SLICE_LENGTH = 50

# for User
USERNAME_LENGTH = 150
FIRST_NAME_LENGTH = 150
LAST_NAME_LENGTH = 150
EMAIL_LENGTH = 254
ROLE_LENGTH = 128
BIO_LENGTH = 256
CONFIRMATION_CODE_LENGTH = 6
ADMIN_ROLE = 'admin'
MODER_ROLE = 'moderator'
