# Generated by Django 3.2 on 2024-02-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240221_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(default='user', max_length=128, verbose_name='role'),
        ),
    ]
