# Generated by Django 3.2 on 2024-03-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('Пользователь', 'user'), ('Модератор', 'moder'), ('Админ', 'admin'), ('Суперюзер', 'superuser')], default='Пользователь', max_length=28, verbose_name='role'),
        ),
    ]
