# Generated by Django 3.2 on 2024-02-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20240228_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='role',
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.ManyToManyField(blank=True, default='user', related_name='user_set', related_query_name='user', to='user.Role', verbose_name='roles'),
        ),
    ]
