# Generated by Django 3.2 on 2024-03-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20240309_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'default_related_name': 'users', 'ordering': ('username',), 'verbose_name': 'Пользователи', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=9, verbose_name='роль'),
        ),
    ]
