# Generated by Django 3.2 on 2024-02-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20240228_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='user.Role', verbose_name='roles'),
        ),
    ]
