# Generated by Django 3.2 on 2024-02-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
    ]
