# Generated by Django 3.2 on 2024-03-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20240301_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(max_length=50, verbose_name='role'),
        ),
    ]
