# Generated by Django 3.2 on 2024-03-01 17:15

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0009_alter_myuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='role',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
            managers=[
                ('objects', user.models.RoleManager()),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='user.Role', verbose_name='roles'),
        ),
    ]
